jobs:
  build-maven-jars:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
        java-version: 17
        server-id: ossrh
        server-password: CI_DEPLOY_PASSWORD
        server-username: CI_DEPLOY_USERNAME
    - continue-on-error: true
      name: Bump Version Number
      run: 'mvn --no-transfer-progress versions:set versions:commit -DnewVersion="${{
        github.event.inputs.version }}"

        git ls-files | grep ''pom.xml$'' | xargs git add

        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        git config --global user.name "${{ github.actor }}"

        git commit -m "Release Error Prone ${{ github.event.inputs.version }}"

        git tag "v${{ github.event.inputs.version }}"

        echo "TARGET_COMMITISH=$(git rev-parse HEAD)" >> $GITHUB_ENV

        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN
        }}@github.com/google/error-prone.git

        '
    - continue-on-error: true
      env:
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      name: Deploy to Sonatype
      run: mvn --no-transfer-progress -P release clean deploy -Dgpg.passphrase="${{
        secrets.GPG_PASSPHRASE }}"
    - continue-on-error: true
      name: Push tag
      run: 'git push origin "v${{ github.event.inputs.version }}"

        '
    - continue-on-error: true
      name: Draft Release Entry
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        generate_release_notes: true
        name: Error Prone ${{ github.event.input.version }}
        tag_name: v${{ github.event.inputs.version }}
        target_commitish: ${{ env.TARGET_COMMITISH }}
name: Release Error Prone
on:
  repository_dispatch:
    types: trigger-ga___release.yml
